/*
    This file is part of ydotool.
    Copyright (C) 2018-2022 Reimu NotMoe <reimu@sudomaker.com>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/*
    Generated by contrib/gen_keymap.py from the system XKB data
    (ckbcomp). Do not edit by hand.

    First four XKB levels only: base, shift, AltGr, AltGr+Shift.
    Characters that require dead keys are intentionally not mapped;
    keymap_lookup() reports them as unmapped so callers can warn
    instead of typing the wrong character.
*/

#include "keymap.h"

#include <stdio.h>
#include <string.h>

static const struct keydef ascii_us[95] = {
	{KEY_SPACE, 0}, {KEY_1, 1}, {KEY_APOSTROPHE, 1}, {KEY_3, 1}, {KEY_4, 1},
	{KEY_5, 1}, {KEY_7, 1}, {KEY_APOSTROPHE, 0}, {KEY_9, 1}, {KEY_0, 1},
	{KEY_8, 1}, {KEY_EQUAL, 1}, {KEY_COMMA, 0}, {KEY_MINUS, 0}, {KEY_DOT, 0},
	{KEY_SLASH, 0}, {KEY_0, 0}, {KEY_1, 0}, {KEY_2, 0}, {KEY_3, 0},
	{KEY_4, 0}, {KEY_5, 0}, {KEY_6, 0}, {KEY_7, 0}, {KEY_8, 0},
	{KEY_9, 0}, {KEY_SEMICOLON, 1}, {KEY_SEMICOLON, 0}, {KEY_COMMA, 1}, {KEY_EQUAL, 0},
	{KEY_DOT, 1}, {KEY_SLASH, 1}, {KEY_2, 1}, {KEY_A, 1}, {KEY_B, 1},
	{KEY_C, 1}, {KEY_D, 1}, {KEY_E, 1}, {KEY_F, 1}, {KEY_G, 1},
	{KEY_H, 1}, {KEY_I, 1}, {KEY_J, 1}, {KEY_K, 1}, {KEY_L, 1},
	{KEY_M, 1}, {KEY_N, 1}, {KEY_O, 1}, {KEY_P, 1}, {KEY_Q, 1},
	{KEY_R, 1}, {KEY_S, 1}, {KEY_T, 1}, {KEY_U, 1}, {KEY_V, 1},
	{KEY_W, 1}, {KEY_X, 1}, {KEY_Y, 1}, {KEY_Z, 1}, {KEY_LEFTBRACE, 0},
	{KEY_BACKSLASH, 0}, {KEY_RIGHTBRACE, 0}, {KEY_6, 1}, {KEY_MINUS, 1}, {KEY_GRAVE, 0},
	{KEY_A, 0}, {KEY_B, 0}, {KEY_C, 0}, {KEY_D, 0}, {KEY_E, 0},
	{KEY_F, 0}, {KEY_G, 0}, {KEY_H, 0}, {KEY_I, 0}, {KEY_J, 0},
	{KEY_K, 0}, {KEY_L, 0}, {KEY_M, 0}, {KEY_N, 0}, {KEY_O, 0},
	{KEY_P, 0}, {KEY_Q, 0}, {KEY_R, 0}, {KEY_S, 0}, {KEY_T, 0},
	{KEY_U, 0}, {KEY_V, 0}, {KEY_W, 0}, {KEY_X, 0}, {KEY_Y, 0},
	{KEY_Z, 0}, {KEY_LEFTBRACE, 1}, {KEY_BACKSLASH, 1}, {KEY_RIGHTBRACE, 1}, {KEY_GRAVE, 1},
};

static const struct keyext ext_us[] = {
	{0x00a6, {KEY_102ND, 3}},
};

static const struct keydef ascii_de[95] = {
	{KEY_SPACE, 0}, {KEY_1, 1}, {KEY_2, 1}, {KEY_BACKSLASH, 0}, {KEY_4, 1},
	{KEY_5, 1}, {KEY_6, 1}, {KEY_BACKSLASH, 1}, {KEY_8, 1}, {KEY_9, 1},
	{KEY_RIGHTBRACE, 1}, {KEY_RIGHTBRACE, 0}, {KEY_COMMA, 0}, {KEY_SLASH, 0}, {KEY_DOT, 0},
	{KEY_7, 1}, {KEY_0, 0}, {KEY_1, 0}, {KEY_2, 0}, {KEY_3, 0},
	{KEY_4, 0}, {KEY_5, 0}, {KEY_6, 0}, {KEY_7, 0}, {KEY_8, 0},
	{KEY_9, 0}, {KEY_DOT, 1}, {KEY_COMMA, 1}, {KEY_102ND, 0}, {KEY_0, 1},
	{KEY_102ND, 1}, {KEY_MINUS, 1}, {KEY_Q, 2}, {KEY_A, 1}, {KEY_B, 1},
	{KEY_C, 1}, {KEY_D, 1}, {KEY_E, 1}, {KEY_F, 1}, {KEY_G, 1},
	{KEY_H, 1}, {KEY_I, 1}, {KEY_J, 1}, {KEY_K, 1}, {KEY_L, 1},
	{KEY_M, 1}, {KEY_N, 1}, {KEY_O, 1}, {KEY_P, 1}, {KEY_Q, 1},
	{KEY_R, 1}, {KEY_S, 1}, {KEY_T, 1}, {KEY_U, 1}, {KEY_V, 1},
	{KEY_W, 1}, {KEY_X, 1}, {KEY_Z, 1}, {KEY_Y, 1}, {KEY_8, 2},
	{KEY_MINUS, 2}, {KEY_9, 2}, {0, 0}, {KEY_SLASH, 1}, {0, 0},
	{KEY_A, 0}, {KEY_B, 0}, {KEY_C, 0}, {KEY_D, 0}, {KEY_E, 0},
	{KEY_F, 0}, {KEY_G, 0}, {KEY_H, 0}, {KEY_I, 0}, {KEY_J, 0},
	{KEY_K, 0}, {KEY_L, 0}, {KEY_M, 0}, {KEY_N, 0}, {KEY_O, 0},
	{KEY_P, 0}, {KEY_Q, 0}, {KEY_R, 0}, {KEY_S, 0}, {KEY_T, 0},
	{KEY_U, 0}, {KEY_V, 0}, {KEY_W, 0}, {KEY_X, 0}, {KEY_Z, 0},
	{KEY_Y, 0}, {KEY_7, 2}, {KEY_102ND, 2}, {KEY_0, 2}, {KEY_RIGHTBRACE, 2},
};

static const struct keyext ext_de[] = {
	{0x00a1, {KEY_1, 3}},
	{0x00a2, {KEY_C, 2}},
	{0x00a3, {KEY_3, 3}},
	{0x00a4, {KEY_4, 3}},
	{0x00a5, {KEY_Y, 3}},
	{0x00a7, {KEY_3, 1}},
	{0x00a9, {KEY_C, 3}},
	{0x00aa, {KEY_F, 3}},
	{0x00ab, {KEY_X, 2}},
	{0x00ac, {KEY_6, 2}},
	{0x00ae, {KEY_R, 3}},
	{0x00af, {KEY_RIGHTBRACE, 3}},
	{0x00b0, {KEY_0, 3}},
	{0x00b1, {KEY_9, 3}},
	{0x00b2, {KEY_2, 2}},
	{0x00b3, {KEY_3, 2}},
	{0x00b5, {KEY_M, 2}},
	{0x00b6, {KEY_R, 2}},
	{0x00b7, {KEY_COMMA, 2}},
	{0x00b9, {KEY_1, 2}},
	{0x00ba, {KEY_M, 3}},
	{0x00bb, {KEY_Z, 2}},
	{0x00bc, {KEY_4, 2}},
	{0x00bd, {KEY_5, 2}},
	{0x00bf, {KEY_MINUS, 3}},
	{0x00c4, {KEY_APOSTROPHE, 1}},
	{0x00c6, {KEY_A, 3}},
	{0x00d0, {KEY_D, 3}},
	{0x00d6, {KEY_SEMICOLON, 1}},
	{0x00d7, {KEY_COMMA, 3}},
	{0x00d8, {KEY_O, 3}},
	{0x00dc, {KEY_LEFTBRACE, 1}},
	{0x00de, {KEY_P, 3}},
	{0x00df, {KEY_MINUS, 0}},
	{0x00e4, {KEY_APOSTROPHE, 0}},
	{0x00e6, {KEY_A, 2}},
	{0x00f0, {KEY_D, 2}},
	{0x00f6, {KEY_SEMICOLON, 0}},
	{0x00f7, {KEY_DOT, 3}},
	{0x00f8, {KEY_O, 2}},
	{0x00fc, {KEY_LEFTBRACE, 0}},
	{0x00fe, {KEY_P, 2}},
	{0x0111, {KEY_F, 2}},
	{0x0126, {KEY_H, 3}},
	{0x0127, {KEY_H, 2}},
	{0x0131, {KEY_I, 3}},
	{0x0138, {KEY_K, 2}},
	{0x0141, {KEY_L, 3}},
	{0x0142, {KEY_L, 2}},
	{0x014a, {KEY_G, 3}},
	{0x014b, {KEY_G, 2}},
	{0x0166, {KEY_T, 3}},
	{0x0167, {KEY_T, 2}},
	{0x017f, {KEY_W, 2}},
	{0x03a9, {KEY_Q, 3}},
	{0x1e9e, {KEY_S, 3}},
	{0x2013, {KEY_SLASH, 2}},
	{0x2014, {KEY_SLASH, 3}},
	{0x2018, {KEY_B, 3}},
	{0x2019, {KEY_BACKSLASH, 2}},
	{0x201a, {KEY_V, 3}},
	{0x201c, {KEY_B, 2}},
	{0x201d, {KEY_N, 2}},
	{0x201e, {KEY_V, 2}},
	{0x2026, {KEY_DOT, 2}},
	{0x2032, {KEY_GRAVE, 2}},
	{0x2033, {KEY_GRAVE, 3}},
	{0x2039, {KEY_X, 3}},
	{0x203a, {KEY_Z, 3}},
	{0x20ac, {KEY_E, 2}},
	{0x2122, {KEY_8, 3}},
	{0x215b, {KEY_2, 3}},
	{0x215c, {KEY_5, 3}},
	{0x215d, {KEY_6, 3}},
	{0x215e, {KEY_7, 3}},
	{0x2190, {KEY_Y, 2}},
	{0x2191, {KEY_U, 3}},
	{0x2192, {KEY_I, 2}},
	{0x2193, {KEY_U, 2}},
};

static const struct keydef ascii_fr[95] = {
	{KEY_SPACE, 0}, {KEY_SLASH, 0}, {KEY_3, 0}, {KEY_3, 2}, {KEY_4, 3},
	{KEY_APOSTROPHE, 1}, {KEY_1, 0}, {KEY_4, 0}, {KEY_5, 0}, {KEY_MINUS, 0},
	{KEY_BACKSLASH, 0}, {KEY_EQUAL, 1}, {KEY_M, 0}, {KEY_6, 0}, {KEY_COMMA, 1},
	{KEY_DOT, 1}, {KEY_0, 1}, {KEY_1, 1}, {KEY_2, 1}, {KEY_3, 1},
	{KEY_4, 1}, {KEY_5, 1}, {KEY_6, 1}, {KEY_7, 1}, {KEY_8, 1},
	{KEY_9, 1}, {KEY_DOT, 0}, {KEY_COMMA, 0}, {KEY_W, 3}, {KEY_EQUAL, 0},
	{KEY_X, 3}, {KEY_M, 1}, {KEY_0, 2}, {KEY_Q, 1}, {KEY_B, 1},
	{KEY_C, 1}, {KEY_D, 1}, {KEY_E, 1}, {KEY_F, 1}, {KEY_G, 1},
	{KEY_H, 1}, {KEY_I, 1}, {KEY_J, 1}, {KEY_K, 1}, {KEY_L, 1},
	{KEY_SEMICOLON, 1}, {KEY_N, 1}, {KEY_O, 1}, {KEY_P, 1}, {KEY_A, 1},
	{KEY_R, 1}, {KEY_S, 1}, {KEY_T, 1}, {KEY_U, 1}, {KEY_V, 1},
	{KEY_Z, 1}, {KEY_X, 1}, {KEY_Y, 1}, {KEY_W, 1}, {KEY_5, 2},
	{KEY_8, 2}, {KEY_MINUS, 2}, {KEY_9, 2}, {KEY_8, 0}, {KEY_7, 2},
	{KEY_Q, 0}, {KEY_B, 0}, {KEY_C, 0}, {KEY_D, 0}, {KEY_E, 0},
	{KEY_F, 0}, {KEY_G, 0}, {KEY_H, 0}, {KEY_I, 0}, {KEY_J, 0},
	{KEY_K, 0}, {KEY_L, 0}, {KEY_SEMICOLON, 0}, {KEY_N, 0}, {KEY_O, 0},
	{KEY_P, 0}, {KEY_A, 0}, {KEY_R, 0}, {KEY_S, 0}, {KEY_T, 0},
	{KEY_U, 0}, {KEY_V, 0}, {KEY_Z, 0}, {KEY_X, 0}, {KEY_Y, 0},
	{KEY_W, 0}, {KEY_4, 2}, {KEY_6, 2}, {KEY_EQUAL, 2}, {KEY_2, 2},
};

static const struct keyext ext_fr[] = {
	{0x00a1, {KEY_1, 3}},
	{0x00a2, {KEY_E, 3}},
	{0x00a3, {KEY_3, 3}},
	{0x00a4, {KEY_RIGHTBRACE, 2}},
	{0x00a5, {KEY_Y, 3}},
	{0x00a6, {KEY_102ND, 3}},
	{0x00a7, {KEY_SLASH, 1}},
	{0x00a9, {KEY_C, 3}},
	{0x00aa, {KEY_F, 3}},
	{0x00ab, {KEY_W, 2}},
	{0x00ac, {KEY_GRAVE, 2}},
	{0x00ae, {KEY_R, 3}},
	{0x00b0, {KEY_0, 3}},
	{0x00b1, {KEY_9, 3}},
	{0x00b2, {KEY_GRAVE, 0}},
	{0x00b5, {KEY_SEMICOLON, 2}},
	{0x00b6, {KEY_R, 2}},
	{0x00b7, {KEY_DOT, 2}},
	{0x00b9, {KEY_1, 2}},
	{0x00ba, {KEY_SEMICOLON, 3}},
	{0x00bb, {KEY_X, 2}},
	{0x00bf, {KEY_MINUS, 3}},
	{0x00c6, {KEY_Q, 3}},
	{0x00d0, {KEY_D, 3}},
	{0x00d7, {KEY_COMMA, 3}},
	{0x00d8, {KEY_O, 3}},
	{0x00de, {KEY_P, 3}},
	{0x00df, {KEY_S, 2}},
	{0x00e0, {KEY_0, 0}},
	{0x00e6, {KEY_Q, 2}},
	{0x00e7, {KEY_9, 0}},
	{0x00e8, {KEY_7, 0}},
	{0x00e9, {KEY_2, 0}},
	{0x00f0, {KEY_D, 2}},
	{0x00f7, {KEY_DOT, 3}},
	{0x00f8, {KEY_O, 2}},
	{0x00f9, {KEY_APOSTROPHE, 0}},
	{0x00fe, {KEY_P, 2}},
	{0x0111, {KEY_F, 2}},
	{0x0126, {KEY_H, 3}},
	{0x0127, {KEY_H, 2}},
	{0x0131, {KEY_I, 3}},
	{0x0138, {KEY_K, 2}},
	{0x0141, {KEY_L, 3}},
	{0x0142, {KEY_L, 2}},
	{0x014a, {KEY_G, 3}},
	{0x014b, {KEY_G, 2}},
	{0x0166, {KEY_T, 3}},
	{0x0167, {KEY_T, 2}},
	{0x03a9, {KEY_A, 3}},
	{0x1e9e, {KEY_S, 3}},
	{0x2018, {KEY_B, 3}},
	{0x2019, {KEY_N, 3}},
	{0x201a, {KEY_V, 3}},
	{0x201c, {KEY_B, 2}},
	{0x201d, {KEY_N, 2}},
	{0x201e, {KEY_V, 2}},
	{0x2022, {KEY_COMMA, 2}},
	{0x20ac, {KEY_E, 2}},
	{0x2122, {KEY_8, 3}},
	{0x215b, {KEY_2, 3}},
	{0x215c, {KEY_5, 3}},
	{0x215d, {KEY_6, 3}},
	{0x215e, {KEY_7, 3}},
	{0x2190, {KEY_Y, 2}},
	{0x2191, {KEY_U, 3}},
	{0x2192, {KEY_I, 2}},
	{0x2193, {KEY_U, 2}},
};

static const struct keydef ascii_dvorak[95] = {
	{KEY_SPACE, 0}, {KEY_1, 1}, {KEY_Q, 1}, {KEY_3, 1}, {KEY_4, 1},
	{KEY_5, 1}, {KEY_7, 1}, {KEY_Q, 0}, {KEY_9, 1}, {KEY_0, 1},
	{KEY_8, 1}, {KEY_RIGHTBRACE, 1}, {KEY_W, 0}, {KEY_APOSTROPHE, 0}, {KEY_E, 0},
	{KEY_LEFTBRACE, 0}, {KEY_0, 0}, {KEY_1, 0}, {KEY_2, 0}, {KEY_3, 0},
	{KEY_4, 0}, {KEY_5, 0}, {KEY_6, 0}, {KEY_7, 0}, {KEY_8, 0},
	{KEY_9, 0}, {KEY_Z, 1}, {KEY_Z, 0}, {KEY_W, 1}, {KEY_RIGHTBRACE, 0},
	{KEY_E, 1}, {KEY_LEFTBRACE, 1}, {KEY_2, 1}, {KEY_A, 1}, {KEY_N, 1},
	{KEY_I, 1}, {KEY_H, 1}, {KEY_D, 1}, {KEY_Y, 1}, {KEY_U, 1},
	{KEY_J, 1}, {KEY_G, 1}, {KEY_C, 1}, {KEY_V, 1}, {KEY_P, 1},
	{KEY_M, 1}, {KEY_L, 1}, {KEY_S, 1}, {KEY_R, 1}, {KEY_X, 1},
	{KEY_O, 1}, {KEY_SEMICOLON, 1}, {KEY_K, 1}, {KEY_F, 1}, {KEY_DOT, 1},
	{KEY_COMMA, 1}, {KEY_B, 1}, {KEY_T, 1}, {KEY_SLASH, 1}, {KEY_MINUS, 0},
	{KEY_BACKSLASH, 0}, {KEY_EQUAL, 0}, {KEY_6, 1}, {KEY_APOSTROPHE, 1}, {KEY_GRAVE, 0},
	{KEY_A, 0}, {KEY_N, 0}, {KEY_I, 0}, {KEY_H, 0}, {KEY_D, 0},
	{KEY_Y, 0}, {KEY_U, 0}, {KEY_J, 0}, {KEY_G, 0}, {KEY_C, 0},
	{KEY_V, 0}, {KEY_P, 0}, {KEY_M, 0}, {KEY_L, 0}, {KEY_S, 0},
	{KEY_R, 0}, {KEY_X, 0}, {KEY_O, 0}, {KEY_SEMICOLON, 0}, {KEY_K, 0},
	{KEY_F, 0}, {KEY_DOT, 0}, {KEY_COMMA, 0}, {KEY_B, 0}, {KEY_T, 0},
	{KEY_SLASH, 0}, {KEY_MINUS, 1}, {KEY_BACKSLASH, 1}, {KEY_EQUAL, 1}, {KEY_GRAVE, 1},
};

static const struct keyext ext_dvorak[] = {
	{0x00a6, {KEY_102ND, 3}},
	{0x00b7, {KEY_E, 3}},
};

static const struct keydef ascii_colemak[95] = {
	{KEY_SPACE, 0}, {KEY_1, 1}, {KEY_APOSTROPHE, 1}, {KEY_3, 1}, {KEY_4, 1},
	{KEY_5, 1}, {KEY_7, 1}, {KEY_APOSTROPHE, 0}, {KEY_9, 1}, {KEY_0, 1},
	{KEY_8, 1}, {KEY_EQUAL, 1}, {KEY_COMMA, 0}, {KEY_MINUS, 0}, {KEY_DOT, 0},
	{KEY_SLASH, 0}, {KEY_0, 0}, {KEY_1, 0}, {KEY_2, 0}, {KEY_3, 0},
	{KEY_4, 0}, {KEY_5, 0}, {KEY_6, 0}, {KEY_7, 0}, {KEY_8, 0},
	{KEY_9, 0}, {KEY_P, 1}, {KEY_P, 0}, {KEY_COMMA, 1}, {KEY_EQUAL, 0},
	{KEY_DOT, 1}, {KEY_SLASH, 1}, {KEY_2, 1}, {KEY_A, 1}, {KEY_B, 1},
	{KEY_C, 1}, {KEY_G, 1}, {KEY_K, 1}, {KEY_E, 1}, {KEY_T, 1},
	{KEY_H, 1}, {KEY_L, 1}, {KEY_Y, 1}, {KEY_N, 1}, {KEY_U, 1},
	{KEY_M, 1}, {KEY_J, 1}, {KEY_SEMICOLON, 1}, {KEY_R, 1}, {KEY_Q, 1},
	{KEY_S, 1}, {KEY_D, 1}, {KEY_F, 1}, {KEY_I, 1}, {KEY_V, 1},
	{KEY_W, 1}, {KEY_X, 1}, {KEY_O, 1}, {KEY_Z, 1}, {KEY_LEFTBRACE, 0},
	{KEY_BACKSLASH, 0}, {KEY_RIGHTBRACE, 0}, {KEY_6, 1}, {KEY_MINUS, 1}, {KEY_GRAVE, 0},
	{KEY_A, 0}, {KEY_B, 0}, {KEY_C, 0}, {KEY_G, 0}, {KEY_K, 0},
	{KEY_E, 0}, {KEY_T, 0}, {KEY_H, 0}, {KEY_L, 0}, {KEY_Y, 0},
	{KEY_N, 0}, {KEY_U, 0}, {KEY_M, 0}, {KEY_J, 0}, {KEY_SEMICOLON, 0},
	{KEY_R, 0}, {KEY_Q, 0}, {KEY_S, 0}, {KEY_D, 0}, {KEY_F, 0},
	{KEY_I, 0}, {KEY_V, 0}, {KEY_W, 0}, {KEY_X, 0}, {KEY_O, 0},
	{KEY_Z, 0}, {KEY_LEFTBRACE, 1}, {KEY_BACKSLASH, 1}, {KEY_RIGHTBRACE, 1}, {KEY_T, 3},
};

static const struct keyext ext_colemak[] = {
	{0x00a0, {KEY_SPACE, 3}},
	{0x00a1, {KEY_1, 2}},
	{0x00a2, {KEY_4, 2}},
	{0x00a3, {KEY_4, 3}},
	{0x00a5, {KEY_5, 3}},
	{0x00aa, {KEY_3, 2}},
	{0x00ab, {KEY_LEFTBRACE, 2}},
	{0x00b2, {KEY_2, 3}},
	{0x00b3, {KEY_3, 3}},
	{0x00b9, {KEY_1, 3}},
	{0x00ba, {KEY_2, 2}},
	{0x00bb, {KEY_RIGHTBRACE, 2}},
	{0x00bf, {KEY_SLASH, 2}},
	{0x00c1, {KEY_A, 3}},
	{0x00c3, {KEY_E, 3}},
	{0x00c4, {KEY_Q, 3}},
	{0x00c5, {KEY_W, 3}},
	{0x00c6, {KEY_Z, 3}},
	{0x00c7, {KEY_C, 3}},
	{0x00c9, {KEY_K, 3}},
	{0x00cd, {KEY_L, 3}},
	{0x00d0, {KEY_7, 3}},
	{0x00d1, {KEY_J, 3}},
	{0x00d3, {KEY_SEMICOLON, 3}},
	{0x00d5, {KEY_APOSTROPHE, 3}},
	{0x00d6, {KEY_P, 3}},
	{0x00d7, {KEY_EQUAL, 2}},
	{0x00d8, {KEY_R, 3}},
	{0x00da, {KEY_I, 3}},
	{0x00dc, {KEY_O, 3}},
	{0x00de, {KEY_8, 3}},
	{0x00df, {KEY_D, 2}},
	{0x00e1, {KEY_A, 2}},
	{0x00e3, {KEY_E, 2}},
	{0x00e4, {KEY_Q, 2}},
	{0x00e5, {KEY_W, 2}},
	{0x00e6, {KEY_Z, 2}},
	{0x00e7, {KEY_C, 2}},
	{0x00e9, {KEY_K, 2}},
	{0x00ed, {KEY_L, 2}},
	{0x00f0, {KEY_7, 2}},
	{0x00f1, {KEY_J, 2}},
	{0x00f3, {KEY_SEMICOLON, 2}},
	{0x00f5, {KEY_APOSTROPHE, 2}},
	{0x00f6, {KEY_P, 2}},
	{0x00f7, {KEY_EQUAL, 3}},
	{0x00f8, {KEY_R, 2}},
	{0x00fa, {KEY_I, 2}},
	{0x00fc, {KEY_O, 2}},
	{0x00fe, {KEY_8, 2}},
	{0x0110, {KEY_Y, 3}},
	{0x0111, {KEY_Y, 2}},
	{0x0126, {KEY_6, 3}},
	{0x0127, {KEY_6, 2}},
	{0x0141, {KEY_U, 3}},
	{0x0142, {KEY_U, 2}},
	{0x0152, {KEY_V, 3}},
	{0x0153, {KEY_V, 2}},
	{0x1e9e, {KEY_D, 3}},
	{0x2013, {KEY_MINUS, 2}},
	{0x2014, {KEY_MINUS, 3}},
	{0x2018, {KEY_9, 2}},
	{0x2019, {KEY_0, 2}},
	{0x201c, {KEY_9, 3}},
	{0x201d, {KEY_0, 3}},
	{0x2039, {KEY_LEFTBRACE, 3}},
	{0x203a, {KEY_RIGHTBRACE, 3}},
	{0x20ac, {KEY_5, 2}},
};

static const struct keymap keymaps[] = {
	{"us", ascii_us, ext_us, 1},
	{"de", ascii_de, ext_de, 79},
	{"fr", ascii_fr, ext_fr, 68},
	{"dvorak", ascii_dvorak, ext_dvorak, 2},
	{"colemak", ascii_colemak, ext_colemak, 68},
};

const struct keymap *keymap_get(const char *name) {
	for (size_t i = 0; i < sizeof(keymaps) / sizeof(keymaps[0]); i++) {
		if (strcmp(keymaps[i].name, name) == 0)
			return &keymaps[i];
	}

	return NULL;
}

bool keymap_lookup(const struct keymap *km, uint32_t cp, struct keydef *out) {
	if (!km)
		return false;

	if (cp >= 0x20 && cp <= 0x7e) {
		struct keydef d = km->ascii[cp - 0x20];

		if (d.code == 0)
			return false;

		*out = d;
		return true;
	}

	for (size_t i = 0; i < km->ext_len; i++) {
		if (km->ext[i].cp == cp) {
			*out = km->ext[i].def;
			return true;
		}
	}

	return false;
}

void keymap_print_list(FILE *f) {
	for (size_t i = 0; i < sizeof(keymaps) / sizeof(keymaps[0]); i++) {
		fprintf(f, "%s%s", i ? ", " : "", keymaps[i].name);
	}
}
