#!/usr/bin/env python3
"""Generate Client/keymap.c from the system XKB data via ckbcomp.

Usage: python3 contrib/gen_keymap.py > Client/keymap.c

Requires ckbcomp (Debian/Ubuntu: console-setup). The generated file is
committed, so building ydotool does not need ckbcomp.

Each layout is reduced to the first four XKB levels: base, shift, AltGr,
AltGr+Shift. Characters that are only reachable through dead keys are not
mapped; keymap_lookup() reports them as unmapped so callers can warn
instead of typing the wrong character.
"""

import re
import subprocess
import sys

LAYOUTS = [
    ("us", ["-layout", "us"]),
    ("de", ["-layout", "de"]),
    ("fr", ["-layout", "fr"]),
    ("dvorak", ["-layout", "us", "-variant", "dvorak"]),
    ("colemak", ["-layout", "us", "-variant", "colemak"]),
]

MODS = ["", "S", "A", "SA"]
MOD_BITS = {"": 0, "S": 1, "A": 2, "SA": 3}

KEYCODE_RE = re.compile(r"^keycode\s+(\d+)\s*=\s*(.+)$")


def evdev_names(path="/usr/include/linux/input-event-codes.h"):
    """Map evdev code -> first KEY_* macro name."""
    names = {}
    pat = re.compile(r"^#define\s+(KEY_[A-Z0-9_]+)\s+(0x[0-9a-fA-F]+|\d+)\s*$")
    with open(path) as f:
        for line in f:
            m = pat.match(line)
            if not m:
                continue
            name = m.group(1)
            if name.startswith("KEY_MAX") or name.startswith("KEY_CNT"):
                continue
            code = int(m.group(2), 0)
            names.setdefault(code, name)
    return names


def symbol_codepoint(tok):
    tok = tok.lstrip("+-")
    if tok == "space":
        return 0x20
    if tok.startswith("U+"):
        try:
            cp = int(tok[2:], 16)
        except ValueError:
            return None
        return cp if cp >= 0x20 else None
    return None


def parse_layout(args):
    out = subprocess.run(
        ["ckbcomp"] + args, capture_output=True, text=True, check=True
    ).stdout
    keys = {}
    for line in out.splitlines():
        m = KEYCODE_RE.match(line.strip())
        if not m:
            continue
        code = int(m.group(1))
        levels = m.group(2).split()[:4]
        while len(levels) < 4:
            levels.append("")
        keys[code] = levels
    return keys


def build_mapping(keys):
    mapping = {}
    for code in sorted(keys):
        for mods, tok in zip(MODS, keys[code]):
            cp = symbol_codepoint(tok)
            if cp is None:
                continue
            mapping.setdefault(cp, (code, mods))
    return mapping


def main():
    names = evdev_names()
    layouts = []
    for layout, args in LAYOUTS:
        mapping = build_mapping(parse_layout(args))
        ascii_entries = []
        for cp in range(0x20, 0x7F):
            code, mods = mapping.get(cp, (None, None))
            if code is None or code not in names:
                ascii_entries.append("{0, 0}")
            else:
                ascii_entries.append("{%s, %d}" % (names[code], MOD_BITS[mods]))
        ext = []
        for cp in sorted(mapping):
            if cp <= 0x7E:
                continue
            code, mods = mapping[cp]
            if code not in names:
                continue
            ext.append((cp, names[code], MOD_BITS[mods]))
        layouts.append((layout, ascii_entries, ext))

    out = []
    out.append("/*")
    out.append("    This file is part of ydotool.")
    out.append("    Copyright (C) 2018-2022 Reimu NotMoe <reimu@sudomaker.com>")
    out.append("")
    out.append("    This program is free software: you can redistribute it and/or modify")
    out.append("    it under the terms of the GNU Affero General Public License as")
    out.append("    published by the Free Software Foundation, either version 3 of the")
    out.append("    License, or (at your option) any later version.")
    out.append("")
    out.append("    This program is distributed in the hope that it will be useful,")
    out.append("    but WITHOUT ANY WARRANTY; without even the implied warranty of")
    out.append("    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the")
    out.append("    GNU Affero General Public License for more details.")
    out.append("")
    out.append("    You should have received a copy of the GNU Affero General Public License")
    out.append("    along with this program.  If not, see <https://www.gnu.org/licenses/>.")
    out.append("*/")
    out.append("")
    out.append("/*")
    out.append("    Generated by contrib/gen_keymap.py from the system XKB data")
    out.append("    (ckbcomp). Do not edit by hand.")
    out.append("")
    out.append("    First four XKB levels only: base, shift, AltGr, AltGr+Shift.")
    out.append("    Characters that require dead keys are intentionally not mapped;")
    out.append("    keymap_lookup() reports them as unmapped so callers can warn")
    out.append("    instead of typing the wrong character.")
    out.append("*/")
    out.append("")
    out.append('#include "keymap.h"')
    out.append("")
    out.append("#include <stdio.h>")
    out.append("#include <string.h>")
    out.append("")

    ext_names = []
    for layout, ascii_entries, ext in layouts:
        out.append("static const struct keydef ascii_%s[95] = {" % layout)
        for i in range(0, 95, 5):
            out.append("\t" + ", ".join(ascii_entries[i:i + 5]) + ",")
        out.append("};")
        out.append("")
        if ext:
            out.append("static const struct keyext ext_%s[] = {" % layout)
            for cp, name, mods in ext:
                out.append("\t{0x%04x, {%s, %d}}," % (cp, name, mods))
            out.append("};")
            out.append("")
            ext_names.append("ext_%s" % layout)
        else:
            ext_names.append("NULL")

    out.append("static const struct keymap keymaps[] = {")
    for (layout, _, ext), ext_name in zip(layouts, ext_names):
        out.append('\t{"%s", ascii_%s, %s, %d},' % (layout, layout, ext_name, len(ext)))
    out.append("};")
    out.append("")
    out.append("const struct keymap *keymap_get(const char *name) {")
    out.append("\tfor (size_t i = 0; i < sizeof(keymaps) / sizeof(keymaps[0]); i++) {")
    out.append("\t\tif (strcmp(keymaps[i].name, name) == 0)")
    out.append("\t\t\treturn &keymaps[i];")
    out.append("\t}")
    out.append("")
    out.append("\treturn NULL;")
    out.append("}")
    out.append("")
    out.append("bool keymap_lookup(const struct keymap *km, uint32_t cp, struct keydef *out) {")
    out.append("\tif (!km)")
    out.append("\t\treturn false;")
    out.append("")
    out.append("\tif (cp >= 0x20 && cp <= 0x7e) {")
    out.append("\t\tstruct keydef d = km->ascii[cp - 0x20];")
    out.append("")
    out.append("\t\tif (d.code == 0)")
    out.append("\t\t\treturn false;")
    out.append("")
    out.append("\t\t*out = d;")
    out.append("\t\treturn true;")
    out.append("\t}")
    out.append("")
    out.append("\tfor (size_t i = 0; i < km->ext_len; i++) {")
    out.append("\t\tif (km->ext[i].cp == cp) {")
    out.append("\t\t\t*out = km->ext[i].def;")
    out.append("\t\t\treturn true;")
    out.append("\t\t}")
    out.append("\t}")
    out.append("")
    out.append("\treturn false;")
    out.append("}")
    out.append("")
    out.append("void keymap_print_list(FILE *f) {")
    out.append("\tfor (size_t i = 0; i < sizeof(keymaps) / sizeof(keymaps[0]); i++) {")
    out.append('\t\tfprintf(f, "%s%s", i ? ", " : "", keymaps[i].name);')
    out.append("\t}")
    out.append("}")
    out.append("")

    sys.stdout.write("\n".join(out))


if __name__ == "__main__":
    main()
